[package]
name = "oxid_maf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fffx = "0.1.3"
clap = { version =  "4.5", features = ["derive"] }
gxhash = "3.4.1"