[package]
name = "oxid_maf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fffx = "0.1.2"
clap = { version =  "4.3.0", features = ["derive"] }
gxhash = "2.2.5"